version: '3.8'
services:
    app:
        container_name: solawind
        image: golang:1.16.3-alpine
        volumes: 
            - .:/go/src/solawind
        working_dir: /go/src/solawind        
        networks: 
            - fullstack
        command: go run ./cmd/main.go
networks: 
    fullstack:
        driver: bridge  